db:
  postgresql: "postgresql://postgres:1234@localhost:5432/mydb?schema=privateapp"


app:
  port: 3500
  front: "http://localhost:3000"
  domain: ".test.com"


jwt:
  secret: "private-app-jwt"
  expiresIn: 1000