db:
  postgresql: "postgresql://postgres:1234@localhost:5432/mydb"
  schema: "privateapp"


app:
  port: 3500
  front: "http://localhost:3000"
  domain: ".test.com"


jwt:
  access:
    secret: "f3MRhlKGV6cC4uk5df2iiUN0atlCVgoR"
    expiresIn: "5m"
  refresh:
    secret: "0I65KnEccbNla7mvm2BmP1Ndbc6mARSF"
    expiresIn: "7d"

apikey:
  youtube: "AIzaSyDDe44x6EkzF2V0QOD1gecv929QSjD0dS4"